dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - mysql-5.7-trusty
    packages:
    - google-chrome-stable fluxbox
    - mysql-server
    - mysql-client
sudo: required
language: csharp
solution: RentableItems.Pn.sln
env: DOTNETCORE=2.1
mono: latest
dotnet: 2.0.0
before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -pnew_password
- sudo service mysql restart
install:
- nvm install 8.0.0
- nvm use 8.0.0
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- fluxbox > /dev/null 2>&1 &
script:
- cd eform-client && npm install
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed