dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
sudo: required
language: csharp
mono: latest
dotnet: 2.0.0
install: 
- nvm install 8.0.0
- nvm use 8.0.0
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- fluxbox > /dev/null 2>&1 &
script:
- cd eform-client && npm install
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed